[book]
authors = ["Evian-Zhang"]
title = "Static Keys"
language = "zh-Hans"

[build]
build-dir = "../../book/zh-Hans"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/Evian-Zhang/static-keys"
